name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp -DskipTests package

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            **/target/*.jar
            **/target/*.pom
            !**/original-*.jar